version: '3.8'

services:
  frontend:
    build:
      dockerfile: todo-list-frontend/Dockerfile
      context: todo-list-frontend
    ports:
      - 8034:80
    depends_on:
      - api
  api:
    build:
      context: .
    ports:
      - 8000:8000
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    volumes:
      - ./.docker_env:/app/.env
  migrations:
    build:
      context: .
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./.docker_env:/app/.env

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: todolist
      POSTGRES_DB: todolist
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres-data:/var/Lib/postgresql/data

